sudo: required
language: java
jdk:
- oraclejdk8
services:
  - docker # required, but travis uses older version of docker :(
before_install:
  - docker --version  # document the version travis is using
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
after_success:
  - eval $(aws ecr get-login --no-include-email --region eu-central-1) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker tag vtapadia/aws-ecs-springboot:latest 369256618572.dkr.ecr.eu-central-1.amazonaws.com/vtapadia/aws-ecs-springboot:latest
  - docker push 369256618572.dkr.ecr.eu-central-1.amazonaws.com/vtapadia/aws-ecs-springboot:latest
env:
  global:
  - secure: qLQPKBgm6LPNkNmrdKqWPutvAK4qrgiptCfxrx6NQuLbI4XwzCBt8MiZa5cGS3Z0n4jSUeKxtXXtAOwbX9JDsWIB9F/t40/rPQFWyYj3pOnwJ1Ug0UZ2KXxrmEJSB1CNW6JQdqJA3mAaONV4BqsA7J7U83n3bY4EgOoIpSWdTI7SrshylSKsw6aFrvbfMeiQ+MZPJqi37vEyQUWICo5hGh7bFe4Lw6YHNwxqdU3lQNbfLFKdpw+oXdre0lXNL0Rc5dTClEej/31iH657LFHzt+AAQmov4Erl1tHEu6KV3w7gULqPEfQHt5Sb8ugWsJm6ajXTXj2JrDW1i3MSIz78sAnhtWPa0GWxdU3Cg1LJCjkcAZpHr51+txQwoL0OeR6sFbiMyoHlkEzZn6m9c4QF8V/jxtz+iPuTvsApdUD3Y2qYNktOqT5v5KwNt0rAOPkIJYWc6xTGmOzLbcADcR8rhFrBqhiVROVryvCNK9dJFPWYDvkkGGf23BbyVtKlcwLM0Wsi71vpew8B41ixkMgxHIwvFYF0jCd5jGQCdzticToguhl2KnQQtUJaIoS91CKgi4WwE68IUfOI9YSEALzUo65dmwVn3t567QVmyejoQIKxoizKFpWrTE2usaHoZrf0zDPB1dfRYPWsFV1AUgmFtXVqJ1KmdKEqS6sfaXVPZXA=
  - secure: ZmKVQreN4GpXWt0NP2lctlS4mT8DucxMic8GOTbuO4x7KykAbCciJCwE7wbq8CByxOIY/gAmCckC2pMbpc2uizl6zuHDgotlV8TDus5R60m6ov7MpupINFD6slnx3D9NUr4G2e2A7NlxcdrGjcT/SQ8OOmDWOAuPaX7B2nHoXBvYL+St2Eeg1gjbWH5WAwa9KczikDL/0tPRGiZociYWWtk2DcsojbAcWOdY4zF7O2juTHt1C9JcE7UiVtOcSTDmQZT6rcAPtvie0s37+OB5gjHnZ+p/zm3a1oTCWPTwYsnxgwEVePt61EpCh02cIMcHzMOZiknu6PvbRoOaLdGJF9mQU0pkhXGO8oajmIPbEa2xAONurrPQlALs3TCyy2L9f+Co6qt33m6KIWU5aVVX2u7RxtWlov1abvkgfeH8zHfrin8hOEfE1LrgnYEK1HrVLhaWSurQEeNdwG8t0dt8GHj7cIj5iKAqUwscVdKyPKYCSc0OQCOvdsTiNgEgeijA00sKAQ8/QNCBq+1nv/Fv49U3RI5VE0FPfWvOvIUo9aeoTlCqzG/juhenedTZIngXwgSNt41B+OydYmH1zpdI0W/0xdAJWvvz27cECxFzBOnXO/Us1+hWR4PvPISgSZ55uxdytsIZcUctQkIoBQkU8Bf0gy5bcdsFlkTH0gTC280=
